//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCvProject.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyCvCareerEntities2 : DbContext
    {
        public MyCvCareerEntities2()
            : base("name=MyCvCareerEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<aboutMe> aboutMe { get; set; }
        public virtual DbSet<contact> contact { get; set; }
        public virtual DbSet<members> members { get; set; }
        public virtual DbSet<myCertifications> myCertifications { get; set; }
        public virtual DbSet<myEducations> myEducations { get; set; }
        public virtual DbSet<myExperiences> myExperiences { get; set; }
        public virtual DbSet<myHobbies> myHobbies { get; set; }
        public virtual DbSet<socialMedia> socialMedia { get; set; }
        public virtual DbSet<mySkills> mySkills { get; set; }
    }
}
