//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCvProject.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class socialMedia
    {
        public int id { get; set; }
        public string social_media_name { get; set; }
        public string icon { get; set; }
        public string link { get; set; }
        public Nullable<bool> status_ { get; set; }
    }
}
